

SETUP:
  POSES_FROM: "annotations" # Choose between "annotations" or "predictions"
  ANNOTATIONS_PATH: 'ANNOTATIONS/6_2-experiment3_points.xml'  #if no annotations (preds from inference) leave empty
  PREDS_PATH: 'ANNOTATIONS/6_2-experiment3_preds.json'
  INTRINSICS_FILE: '../physic_overlay_codebase/CALIBRATION/intrinsics.json'
  IMAGES_PATH: '../physic_overlay_codebase/DATA/6_2/GH010483/'
  #  IMAGES_PATH: '../physic_overlay_codebase/DATA/6_2/GH010484/'
  MESH_PATH: 'MESH/repere.json'
  MESH_SIZE: 37   #Repere Size
  LOCAL: True
  DEBUG_OFFSET: 1360 # change to select specific parts of the video, for debugging purposes, if not in use, set it to 0
  # DEBUG_OFFSET : 2173 # frame of error
  # DEBUG_OFFSET : 2734 # frame of error
  # DEBUG_OFFSET : 2400  # start of moving point 2
  # DEBUG_OFFSET : 2700 # testpoint
  # DEBUG_OFFSET : 1300

DISPLAY:
  MOVING_POINTS_DRAW: True

EWMA:
  BETA_SPEED: 0.98